config/routes.rb
Rails.application.routes.draw do

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

 root :to => 'users#index'

 resources :users do
   resources :tweets
   resources :follows
 end

 resources :sessions, :only => [:new, :create]
 resources :tweets


end

app/models/follow.rb
class Follow < ActiveRecord::Base
  belongs_to :user
  belongs_to :followed_user, :class_name => 'User'
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  validates_presence_of :tweet
  belongs_to :user

  default_scope { order('created_at DESC') }

  after_create :check_for_mentions

  def check_for_mentions
    User.all.each do |user|
      if self.tweet.include?("@"+user.username)
        UserMailer.mention(user, self.user.username).deliver
      end
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :username
  validates_presence_of :email
  validates_uniqueness_of :email
  has_secure_password
  has_many :tweets
  has_many :follows
  has_many :followed_users, :through => :follows
  has_many :f_tweets, :through => :followed_users, :source => :tweets

  def followers
    array = []
    Follow.all.each do |follow|
      if self.id == follow.followed_user_id
        array << follow
      end
    end
    array.count
  end

  def self.find_by_search(query)
    result = User.basic_search(query)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private
  def session_show
    session[:user_id]
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
  helper_method :session_show

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

  def new
    @follow = follow.new
  end

  def create
    Follow.create({user_id: current_user.id, followed_user_id: params[:user_id]})
    follower = User.find(params[:user_id])
    UserMailer.following(current_user, follower).deliver
    redirect_to user_path(follower.id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid."
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user_id = current_user.id
    if @tweet.save
      respond_to do |format|
        format.html { redirect_to user_path(@tweet.user_id) }
        format.js
      end
    else
      render "new"
    end
  end

  def destroy
    @tweet = Tweet.find(params[:id])
    @tweet.destroy
    redirect_to root_path
  end

  private

  def tweet_params
    params.require(:tweet).permit(:tweet, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.new
    @tweet = Tweet.new

    if params[:search]
      search = params[:search]
      @results = User.basic_search(search[:query])
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      UserMailer.signup_confirmation(@user).deliver
      session[:user_id] = @user.id
      Follow.create({user_id: current_user.id, followed_user_id: current_user.id})
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @tweet= Tweet.new
  end

  private

  def user_params
    params.require(:user).permit(:email, :username, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
  <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
  <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwitterClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
 <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <div class="navbar-brand"><%= link_to "Timeline", root_path%></div>
      </div>
      <% if current_user != nil %>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav navbar-left">
            <li><%= link_to "Me", user_path(current_user.id)%></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><p class="navbar-text">Logged in as <%= current_user.email %></p></li>
            <li><%= link_to "Log Out", logout_path%></li>
          </ul>
      <% else %>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Sign up", signup_path%></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li><%= link_to "Login", login_path%></li>
          </ul>
        </div>
      <% end %>
    </div>
  </nav>

<body>
  <div class="container">

    <%= yield %>

  </div>

</body>
</html>

app/views/tweets/_form.html.erb
<%= render('layouts/errors', :object => @tweet) %>

<%= form_for @tweet, remote: true do |f| %>
  <div class= "form-group">
    <%= f.label :tweet %>
    <%= f.text_area :tweet, :maxlength => 140, :size => 40, class: "form-control", id: "tweetbox" %>
    <br>
    <span id="tweetsubmit">
    <%= f.submit("Tweet", :class => "btn btn-primary btn-sm") %>
    </span>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div class ="tweet-boarder">
  <% tweeter = '@' + User.find(tweet.user_id).username%>
  <h5><%=link_to tweeter, user_path(tweet.user_id)%></h5>
	<p><%= tweet.tweet %></p>
  <%= link_to image_tag("http://blogs.plos.org/neurotribes/files/2011/11/trashcan.jpg", id: "trash"), tweet_path(tweet.id), method: 'DELETE'  %>
</div>

app/views/tweets/create.js.erb
$('#own-tweets').prepend('<%= j render @tweet %>');
$('#tweetbox').val("");

$('#tweet-deck').prepend('<%= j render @tweet %>');
$('#tweetbox').val("");

app/views/users/_form.html.erb
<%= render('layouts/errors', :object => @user) %>

<%= form_for @user do |f| %>
  <div class= "form-group col-md-4 columns">
    <%= f.label :username %>
    <%= f.text_field :username, class: "form-control" %>
    <%= f.label :email %>
    <%= f.text_field :email, class: "form-control" %>
    <%= f.label :password %>
    <%= f.password_field :password, class: "form-control" %>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: "form-control" %>
    <br>
    <%= f.submit(:class => "btn btn-primary") %>
  </div>
<% end %>

app/views/users/index.html.erb
<%= link_to image_tag("http://nyobetabeat.files.wordpress.com/2014/05/twitter-logo.png", class: "logo"), root_path%>


<% if current_user %>
<div class ="row">
    <div class="col-md-3 columns">
      <img id="egg" src="http://data3.whicdn.com/images/69351265/large.jpg">
      <h2> @<%= current_user.username%> </h2>
      <p>following: <%= current_user.follows.count%></p>
      <div>followers: <%= current_user.followers %> </div>
  </br>
      <%= render 'tweets/form' %>
    </div>
    <div class="col-md-5 columns">
      <h3>Tweet Deck:</h3>
      <div id="tweet-deck">
        <% current_user.f_tweets.each do |tweet| %>
        <div class="tweet-boarder">
          <% tweeter = '@' + User.find(tweet.user_id).username%>
          <h5><%=link_to tweeter, user_path(tweet.user_id)%></h5>
          <p><%= tweet.tweet%></p>
          <% if tweet.user_id == current_user.id %>

          <%= link_to image_tag("http://blogs.plos.org/neurotribes/files/2011/11/trashcan.jpg", id: "trash"), tweet_path(tweet.id), method: 'DELETE'  %>
          <%end%>

        </div>
        <% end %>
      </div>
      <br>
    </div>
    <div class="col-md-3 columns">
        <form action="/" method="get" class="form-group">
          <input name="search[query]" type="text" class="form-control" placeholder="search users"><br>
          <button class="btn btn-primary">search</button>
        </form>

      <% if !@results.nil? %>
        <h5>Results</h5>
        <% @results.each do |result| %>
          <p><%= link_to "@"+result.username, user_path(result.id)%></p>
        <% end %>
      <% end %>
    </div>

</div>
<% else %>
  <%= render 'form'%>
<% end %>

app/views/users/new.html.erb
<%= link_to image_tag("http://nyobetabeat.files.wordpress.com/2014/05/twitter-logo.png", class: "logo"), root_path%>
<h2 class="logo">Sign up</h2>

<%= render 'form' %>

app/views/users/show.html.erb
<%= link_to image_tag("http://nyobetabeat.files.wordpress.com/2014/05/twitter-logo.png", class: "logo"), root_path%>

<div class="row">
<div class="col-md-3 columns">
  <img id="egg" src="http://data3.whicdn.com/images/69351265/large.jpg">
  <h2><%= '@'+@user.username %></h2>

  <%= link_to "Follow", user_follows_path(@user.id), method: "post",  class: "btn btn-primary btn-sm"  %>
  </br>
  </br>
  <p>following: <%= @user.follows.count%></p>
  <div>followers: <%= @user.followers %> </div>
  </br>

  <% if current_user.id == @user.id %>
    <%= render 'tweets/form' %>
  <% end %>
</div>
<div class="col-md-5 columns">
  <h3>Your tweets</h3>
  <div id="own-tweets">
    <%= render @user.tweets %>
  </div>
</div>

<div class="col-md-3 columns">
  <form action="/" method="get" class="form-group">
    <input name="search[query]" type="text" class="form-control" placeholder="search users"><br>
    <button class="btn btn-primary">search</button>
  </form>

  <% if !@results.nil? %>
    <h5>Results</h5>
    <% @results.each do |result| %>
      <p><%= link_to "@"+result.username, user_path(result.id)%></p>
    <% end %>
  <% end %>
</div>
</div>